on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-20.04
    container:
      image: erlang:23.2.5.0-alpine
    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
           apk update
           apk --no-cache upgrade
           apk --no-cache add gcc git libc-dev libc-utils libgcc linux-headers make bash musl-dev musl-utils ncurses-dev pcre2 pkgconf scanelf wget zlib

    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           git init
           git remote add origin https://github.com/travelping/ppplib.git
           git fetch
           git add .
           git checkout $( git tag | tail -1 )
           rebar3 edoc
           rebar3 hex publish -r hexpm --yes
